sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14

cache:
  bundle: true
  directories:
    - node_modules

script:
  - npm install codecov nyc --no-save
  - npm test -- --coverage
after_script:
  - npx codecov --token=$CODECOV_TOKEN
